"""DescFix

Revision ID: 0111269e8128
Revises: ccfa173825e9
Create Date: 2023-01-29 22:17:22.411134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0111269e8128'
down_revision = 'ccfa173825e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
