"""Graph4

Revision ID: 03c27c630d88
Revises: b8f66c59f97b
Create Date: 2023-01-27 22:38:33.848325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c27c630d88'
down_revision = 'b8f66c59f97b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
