"""Graph4

Revision ID: 07359f6f6e48
Revises: 03c27c630d88
Create Date: 2023-01-27 22:42:06.220535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07359f6f6e48'
down_revision = '03c27c630d88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
