"""BorisFirstMigr3

Revision ID: 112ad2e9da55
Revises: 86912d5c6c0f
Create Date: 2023-02-02 23:12:52.255681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '112ad2e9da55'
down_revision = '86912d5c6c0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('marker_lat', sa.Float(), nullable=True))
    op.add_column('poi', sa.Column('marker_lon', sa.Float(), nullable=True))
    op.drop_column('poi', 'market_lat')
    op.drop_column('poi', 'market_lon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('market_lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('poi', sa.Column('market_lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('poi', 'marker_lon')
    op.drop_column('poi', 'marker_lat')
    # ### end Alembic commands ###
