"""Images

Revision ID: 1a2941aa0131
Revises: dbb0be25c7f4
Create Date: 2023-02-10 22:04:35.972499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2941aa0131'
down_revision = 'dbb0be25c7f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('poi_image_key', 'poi', type_='unique')
    op.drop_column('poi', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('image', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('poi_image_key', 'poi', ['image'])
    # ### end Alembic commands ###
