"""DescFix4

Revision ID: 1cc8c5f42e48
Revises: b9bbda2064f8
Create Date: 2023-01-29 22:45:33.105319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc8c5f42e48'
down_revision = 'b9bbda2064f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
