"""history_and_desc

Revision ID: 1d9013cda183
Revises: 5563e5670b54
Create Date: 2023-02-03 22:39:28.976743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9013cda183'
down_revision = '5563e5670b54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi', 'history')
    op.drop_column('poi', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    op.add_column('poi', sa.Column('history', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
