"""Broccol migration

Revision ID: 24bf59548bf6
Revises: ab0d3a2f7bf3
Create Date: 2023-02-19 13:25:23.569404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bf59548bf6'
down_revision = 'ab0d3a2f7bf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('router', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('router', sa.Column('full_time', sa.Integer(), nullable=False))
    op.add_column('router', sa.Column('walk_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('router', 'walk_time')
    op.drop_column('router', 'full_time')
    op.drop_column('router', 'length')
    # ### end Alembic commands ###
