"""history_and_desc

Revision ID: 4d3d8b8df48d
Revises: 8c937faeab9b
Create Date: 2023-02-03 22:37:20.685444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3d8b8df48d'
down_revision = '8c937faeab9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###
