"""DescFix2

Revision ID: 4efd6a1a0713
Revises: 0111269e8128
Create Date: 2023-01-29 22:23:39.661488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efd6a1a0713'
down_revision = '0111269e8128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
