"""history_and_desc

Revision ID: 5563e5670b54
Revises: 4d3d8b8df48d
Create Date: 2023-02-03 22:38:08.762842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5563e5670b54'
down_revision = '4d3d8b8df48d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
