"""Broccol migration

Revision ID: 6d6e1d443d5c
Revises: d97c78a66276
Create Date: 2023-02-15 20:15:10.595610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6e1d443d5c'
down_revision = 'd97c78a66276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('router')
    # ### end Alembic commands ###
