"""Graph

Revision ID: 6fb0e69725c5
Revises: 47e51bf578dd
Create Date: 2023-01-27 21:37:50.292874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb0e69725c5'
down_revision = '47e51bf578dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
