"""Graph2

Revision ID: 7914f4275b0b
Revises: 630f4b964499
Create Date: 2023-01-27 22:25:53.170476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7914f4275b0b'
down_revision = '630f4b964499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
