"""Broccol migration

Revision ID: 7c10fab9d9d8
Revises: f6bbb8a8f623
Create Date: 2023-02-16 20:16:51.221847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c10fab9d9d8'
down_revision = 'f6bbb8a8f623'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_paths', sa.Column('full_time', sa.Integer(), nullable=False))
    op.add_column('saved_paths', sa.Column('walk_time', sa.Integer(), nullable=False))
    op.drop_column('saved_paths', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_paths', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('saved_paths', 'walk_time')
    op.drop_column('saved_paths', 'full_time')
    # ### end Alembic commands ###
