"""PoiType1

Revision ID: 81950d3a575b
Revises: 31420ec9fbba
Create Date: 2023-01-29 21:18:36.088613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81950d3a575b'
down_revision = '31420ec9fbba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('poi', sa.Column('image', sa.String(length=120), nullable=False))
    op.add_column('poi', sa.Column('description', sa.String(length=5000), nullable=False))
    op.create_unique_constraint(None, 'poi', ['description'])
    op.create_unique_constraint(None, 'poi', ['image'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poi', type_='unique')
    op.drop_constraint(None, 'poi', type_='unique')
    op.drop_column('poi', 'description')
    op.drop_column('poi', 'image')
    op.drop_table('poi_type')
    # ### end Alembic commands ###
