"""Graph5

Revision ID: 8289bb8eb7af
Revises: 91fc316be290
Create Date: 2023-01-27 22:46:35.026657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8289bb8eb7af'
down_revision = '91fc316be290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
