"""Graph3

Revision ID: 83813e4aec3a
Revises: 7914f4275b0b
Create Date: 2023-01-27 22:35:33.759713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83813e4aec3a'
down_revision = '7914f4275b0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
