"""Broccol migration

Revision ID: 84b9ec380a60
Revises: f009ccc40c1b
Create Date: 2023-02-19 18:50:44.217661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b9ec380a60'
down_revision = 'f009ccc40c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('image', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'image')
    # ### end Alembic commands ###
