"""BorisFirstMigr2

Revision ID: 86912d5c6c0f
Revises: ee9feb750981
Create Date: 2023-02-02 23:01:27.999349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86912d5c6c0f'
down_revision = 'ee9feb750981'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('poi_short_name_key', 'poi', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('poi_short_name_key', 'poi', ['short_name'])
    # ### end Alembic commands ###
