"""history

Revision ID: 8c937faeab9b
Revises: 112ad2e9da55
Create Date: 2023-02-03 21:58:05.927824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c937faeab9b'
down_revision = '112ad2e9da55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('history', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi', 'history')
    # ### end Alembic commands ###
