"""Broccol migration

Revision ID: a2d536e886fe
Revises: 945d55e48f5d
Create Date: 2023-02-19 20:47:45.574405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d536e886fe'
down_revision = '945d55e48f5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
