"""DescFix6

Revision ID: a2e8e60d7368
Revises: 93bb1d7c34ee
Create Date: 2023-01-29 22:54:35.477731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e8e60d7368'
down_revision = '93bb1d7c34ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
