"""Broccol migration

Revision ID: b1aea3ce5c75
Revises: a2d536e886fe
Create Date: 2023-02-19 20:48:15.922976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1aea3ce5c75'
down_revision = 'a2d536e886fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('walk_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['poi.id'], name='history_owner_id_fkey'),
    sa.PrimaryKeyConstraint('owner_id', name='history_pkey')
    )
    # ### end Alembic commands ###
