"""Graph_finally

Revision ID: b2a2d3f5acb6
Revises: f77f6836ba62
Create Date: 2023-01-27 22:53:11.773423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a2d3f5acb6'
down_revision = 'f77f6836ba62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('distance_list_start_id_fkey', 'distance_list', type_='foreignkey')
    op.drop_constraint('distance_list_end_id_fkey', 'distance_list', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('distance_list_end_id_fkey', 'distance_list', 'poi', ['end_id'], ['id'])
    op.create_foreign_key('distance_list_start_id_fkey', 'distance_list', 'poi', ['start_id'], ['id'])
    # ### end Alembic commands ###
