"""Broccol migration

Revision ID: b2ad6fc9a5ee
Revises: 81db1cc29ecb
Create Date: 2023-02-20 20:47:59.667756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ad6fc9a5ee'
down_revision = '81db1cc29ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('full_time', sa.Integer(), nullable=False),
    sa.Column('walk_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('static_paths', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('static_paths', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.drop_table('saved_paths')
    # ### end Alembic commands ###
