"""Graph4

Revision ID: b8f66c59f97b
Revises: 83813e4aec3a
Create Date: 2023-01-27 22:36:37.195385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f66c59f97b'
down_revision = '83813e4aec3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
