"""DescFix3

Revision ID: b9bbda2064f8
Revises: 4efd6a1a0713
Create Date: 2023-01-29 22:24:39.124944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bbda2064f8'
down_revision = '4efd6a1a0713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
