"""Broccol migration

Revision ID: cdcc4be364b9
Revises: ece03ea76557
Create Date: 2023-02-20 20:43:02.171424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcc4be364b9'
down_revision = 'ece03ea76557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_paths', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_paths', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###
