"""Broccol migration

Revision ID: d97c78a66276
Revises: e7b59f578b3e
Create Date: 2023-02-15 20:11:05.578296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97c78a66276'
down_revision = 'e7b59f578b3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
