"""Images

Revision ID: dbb0be25c7f4
Revises: d72bc0b2391f
Create Date: 2023-02-10 22:02:24.819231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb0be25c7f4'
down_revision = 'd72bc0b2391f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('short_description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi', 'short_description')
    # ### end Alembic commands ###
