"""Images

Revision ID: e7b59f578b3e
Revises: 1a2941aa0131
Create Date: 2023-02-10 22:06:04.997850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b59f578b3e'
down_revision = '1a2941aa0131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('image', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi', 'image')
    # ### end Alembic commands ###
