"""Broccol migration

Revision ID: ece03ea76557
Revises: dab54fc5845a
Create Date: 2023-02-20 20:38:05.937046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece03ea76557'
down_revision = 'dab54fc5845a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_paths', sa.Column('full_time', sa.Integer(), nullable=False))
    op.add_column('static_paths', sa.Column('walk_time', sa.Integer(), nullable=False))
    op.drop_column('static_paths', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_paths', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('static_paths', 'walk_time')
    op.drop_column('static_paths', 'full_time')
    # ### end Alembic commands ###
