"""BorisFirstMigr

Revision ID: ee9feb750981
Revises: a2e8e60d7368
Create Date: 2023-02-02 22:53:05.662124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee9feb750981'
down_revision = 'a2e8e60d7368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('lenght', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tiles', sa.String(length=120), nullable=True),
    sa.Column('attr', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('lenght', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('poi', sa.Column('short_name', sa.String(length=120), nullable=True))
    op.add_column('poi', sa.Column('entrance_lat', sa.Float(), nullable=True))
    op.add_column('poi', sa.Column('entrance_lon', sa.Float(), nullable=True))
    op.add_column('poi', sa.Column('market_lat', sa.Float(), nullable=True))
    op.add_column('poi', sa.Column('market_lon', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'poi', ['short_name'])
    op.drop_column('poi', 'lon')
    op.drop_column('poi', 'lat')
    op.add_column('users', sa.Column('style_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'styles', ['style_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'style_id')
    op.add_column('poi', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('poi', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'poi', type_='unique')
    op.drop_column('poi', 'market_lon')
    op.drop_column('poi', 'market_lat')
    op.drop_column('poi', 'entrance_lon')
    op.drop_column('poi', 'entrance_lat')
    op.drop_column('poi', 'short_name')
    op.drop_table('saved_paths')
    op.drop_table('styles')
    op.drop_table('static_paths')
    # ### end Alembic commands ###
