"""Broccol migration

Revision ID: f009ccc40c1b
Revises: 24bf59548bf6
Create Date: 2023-02-19 18:01:21.929827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f009ccc40c1b'
down_revision = '24bf59548bf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('full_time', sa.Integer(), nullable=True),
    sa.Column('walk_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.alter_column('router', 'length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('router', 'full_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('router', 'walk_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('router', 'walk_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('router', 'full_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('router', 'length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('history')
    # ### end Alembic commands ###
