"""Broccol migration

Revision ID: f5bc6929a82f
Revises: 6d6e1d443d5c
Create Date: 2023-02-15 21:24:33.192599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bc6929a82f'
down_revision = '6d6e1d443d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('router', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('router', sa.Column('mandatory_points', sa.String(length=100), nullable=True))
    op.add_column('router', sa.Column('dur_of_visit', sa.Boolean(), nullable=True))
    op.add_column('router', sa.Column('n_of_ans', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('router', 'n_of_ans')
    op.drop_column('router', 'dur_of_visit')
    op.drop_column('router', 'mandatory_points')
    op.drop_column('router', 'time_limit')
    # ### end Alembic commands ###
