"""Broccol migration

Revision ID: f6bbb8a8f623
Revises: f5bc6929a82f
Create Date: 2023-02-16 19:58:19.774594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bbb8a8f623'
down_revision = 'f5bc6929a82f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_paths', sa.Column('length', sa.Integer(), nullable=False))
    op.drop_column('saved_paths', 'lenght')
    op.add_column('static_paths', sa.Column('length', sa.Integer(), nullable=False))
    op.drop_column('static_paths', 'lenght')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_paths', sa.Column('lenght', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('static_paths', 'length')
    op.add_column('saved_paths', sa.Column('lenght', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('saved_paths', 'length')
    # ### end Alembic commands ###
