"""User update

Revision ID: f722d2bbd35b
Revises: 45bc9ba14bd2
Create Date: 2023-01-24 21:47:52.961625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f722d2bbd35b'
down_revision = '45bc9ba14bd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
