"""Graph6

Revision ID: f77f6836ba62
Revises: 8289bb8eb7af
Create Date: 2023-01-27 22:51:34.888727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77f6836ba62'
down_revision = '8289bb8eb7af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
